org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

flutter.minSdkVersion=31
flutter.targetSdkVersion=34
flutter.compileSdkVersion=34

TRACKING_TOKEN_KEY=my-secret-key
TRACKING_TOKEN_VALUE=my-secret-value

